### ISSUE TITLE
help

### ISSUE THREAD

**Issue by love56014** [Synthlight/MHR-Editor#5]
i can't open this.
why

**Comment by Synthlight** [comment]
Maybe you're not extracting the contents and just trying to run the exe from the zip which will never work.
Other than that, no clue. It works for everyone else ¯\\_(ツ)_/¯

You could also try the windows event view and look for a crash log there which may help you but without any actual information...

**Comment by love56014** [comment]
So I have to pull the file to the exe?😂

Synthlight ***@***.***> 於 2022年7月20日 週三 11:30 寫道：

**Comment by Synthlight** [comment]
What? Pull what? I'm pretty sure there's a translation issue here.

You need to **extract the contents of the 7z**. *Then* run the exe. **Do not run the exe from within the archive.**

**Comment by love56014** [comment]
What I mean is that after I run the exe now, it will not open any windows,
but close it directly

Synthlight ***@***.***> 於 2022年7月20日 週三 中午12:00寫道：
